<?php
global $URL_PATH; // Necesitamos la trayectoria de la URL a la app
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>
<?php /* El action es una ruta. Necesita el URL_PATH */?>
<div style="padding-left:5%; padding-right:5%;">
    <form class="mt-4" action="<?=$URL_PATH?>/registro" method="POST" onsubmit="">
        <div class="form-group row">
            <label for="login" class="col-md-2 col-form-label">Login</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="login_usu" value="" name="login_usu"
                pattern="[A-Za-z0-9]{1,20}" title="Sólo letras y números" required
                >
            </div>
        </div>
        <div class="form-group row">
            <label for="pass1" class="col-md-2 col-form-label">Contraseña: </label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="pass1" value="" name="password" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="direccion" class="col-md-2 col-form-label">Direccion</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="direccion" name="direccion" value="" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-md-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" name="email" value="" required>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-danger offset-md-2">Registrarse!</button>
        </div>
    </form>
</div>
    <?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>