<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>

<div class="row m-2">
    <div class="col-5">
        <img class="img-fluid rounded" src="<?= $URL_PATH ?>/assets/<?= $producto->img ?>" alt="Imagen: <?= $producto->descripcion?>">
    </div>
    <div class="col-7">
        <h4><?= $producto->descripcion ?></h4>
        <?php /*Pasamos el id del post al evento de javascript. Enlace solo si usuario logueado*/ ?>
        <?php if (isset($_SESSION["login_usu"])) : ?>
            <a href="javascript:void(0)" onclick="compra(<?= $producto->id ?>)" data-id="<?= $producto->id ?>"><i class="fa fa-shopping-cart"></i></a>
            <?php endif ?>
            <?php /* El atributo id del elemento del corazón tiene como sufijo el id del post */ ?>
            <i id="likecorazon<?= $producto->id ?>" class="fa fa-heart<?= ($post->like ? " text-danger" : "") ?>"></i>
            <?php if (isset($_SESSION["login_usu"])) : ?>
            </a>
        <?php endif ?>
    </div>
     <!-- ********************** Modal ******************************************* -->
 <script>
      function compra(id) {
        console.log("Realizamos compra de Producto con id " + id);
        $('#productosModal').modal('show'); // mostrar div oculto de manera modal. 
        comprarProducto(id);
      }
 </script>
     <div class="modal fade" id="productosModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Producto añadido correctamente al carrito </h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <a href="<?= $URL_PATH ?>/realizarCompra" type="button" class="btn btn-secondary" >Realizar Compra</a>
            <a href="<?= $URL_PATH ?>" type="button" class="btn btn-primary">Seguir Comprando</a>
          </div>
        </div>
      </div>
    </div>
</div>
<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>