<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>
  </div>
  <section class="featured spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Productos en Oferta</h2>
                    </div>
                </div>
            </div>
            <div class="row featured__filter">
              <?php $cuenta=0;
              foreach ($productos as $producto) :?>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="featured__item">
                      <div>
                        <img src="<?=$URL_PATH?>/assets/<?=$producto->img?>" width="280" height="200">
                        <ul class="img_hover">
                        <li><a href="javascript:void(0)" onclick="compra(<?= $producto->id ?>)" data-id="<?= $producto->id ?>"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                      </div>
                        <div class="featured__item__text">
                            <h6><a href="<?=$URL_PATH?>/producto/<?=$producto->id?>"><?=$producto->nombre?></a></h6>
                            <h5><?=$producto->precio?>€</h5>
                        </div>
                    </div>
                </div>
                <?php endforeach?>
            </div>
        </div>
    </section>
 <!-- ********************** Modal ******************************************* -->
 <script>
      function compra(id) {
        console.log("Realizamos compra de Producto con id " + id);
        $('#productosModal').modal('show'); // mostrar div oculto de manera modal. 
        comprarProducto(id);
      }
 </script>


    <div class="modal fade" id="productosModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Producto añadido correctamente al carrito </h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <a href="<?= $URL_PATH ?>/realizarCompra" type="button" class="btn btn-secondary" >Realizar Compra</a>
            <a href="<?= $URL_PATH ?>" type="button" class="btn btn-primary">Seguir Comprando</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</script>


<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>